"""Build distributable, explicitly labelled demo inputs; never generate CV results."""
import hashlib
import json
from pathlib import Path
import subprocess
import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'media'
PHOTO = ROOT.parent / 'vision/tests/fixtures/astronaut.png'
WIDTH, HEIGHT, FPS, PHASE = 1024, 576, 5, 30


def background(title):
    frame = np.full((HEIGHT, WIDTH, 3), 225, np.uint8)
    # Fixed, high-contrast background features make real camera-motion checking
    # meaningful even when the person is absent. Never bypass ViewGuard.
    for y in range(64, HEIGHT-30, 40):
        for x in range(24, WIDTH-20, 40):
            cv2.rectangle(frame, (x, y), (x+8, y+8), (155, 155, 155), -1)
    cv2.rectangle(frame, (0, 0), (WIDTH, 55), (30, 30, 30), -1)
    cv2.putText(frame, 'DEMO INPUT - '+title, (20, 36), cv2.FONT_HERSHEY_SIMPLEX, .75, (255, 255, 255), 2)
    cv2.putText(frame, 'Synthetic scene / real model inference / 90 second loop', (20, 558), cv2.FONT_HERSHEY_SIMPLEX, .55, (30, 30, 30), 1)
    return frame


def scenes():
    instrument = []
    for value in ['70 C', '85.2 C', '72 C']:
        frame = background('INSTRUMENT DISPLAY')
        # Keep the entire OCR crop clear of captions and provide whitespace
        # around a single reading, matching the model's real numeric ROI contract.
        frame[58:536, 530:] = 230
        cv2.putText(frame, value, (560, 310), cv2.FONT_HERSHEY_SIMPLEX, 2.5, (20, 20, 20), 4)
        instrument.append(frame)
    empty = background('RESTRICTED AREA - PUBLIC DOMAIN PHOTO FIXTURE')
    occupied = empty.copy()
    photo = cv2.resize(cv2.imread(str(PHOTO)), (384, 384))
    occupied[112:496, 320:704] = photo
    return {'instrument.mp4': instrument, 'restricted-area.mp4': [empty, occupied, empty]}


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, phases in scenes().items():
        command = ['ffmpeg', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-pixel_format', 'bgr24', '-video_size', f'{WIDTH}x{HEIGHT}', '-framerate', str(FPS), '-i', '-', '-c:v', 'libx264', '-profile:v', 'main', '-bf', '0', '-pix_fmt', 'yuv420p', '-r', str(FPS), '-g', str(FPS), '-crf', '20', '-movflags', '+faststart', str(OUT/name)]
        process = subprocess.Popen(command, stdin=subprocess.PIPE)
        for frame in phases:
            for _ in range(PHASE*FPS):
                process.stdin.write(frame.tobytes())
        process.stdin.close()
        if process.wait() != 0:
            raise RuntimeError('ffmpeg could not encode demo media')
    manifest = {
        'format': 1, 'durationS': PHASE*3, 'fps': FPS, 'width': WIDTH, 'height': HEIGHT,
        'source': {'file': 'integrations/vision/tests/fixtures/astronaut.png', 'sha256': hashlib.sha256(PHOTO.read_bytes()).hexdigest(), 'url': 'https://github.com/scikit-image/scikit-image/blob/v0.25.2/skimage/data/astronaut.png', 'rights': 'NASA Eileen Collins photograph; public domain. Synthetic scene and instrument graphics generated by Plantbot.'},
        'phases': [{'startS': 0, 'endS': 30, 'display': 70.0, 'personPresent': False}, {'startS': 30, 'endS': 60, 'display': 85.2, 'personPresent': True}, {'startS': 60, 'endS': 90, 'display': 72.0, 'personPresent': False}],
        'files': {name: hashlib.sha256((OUT/name).read_bytes()).hexdigest() for name in scenes()},
        'boundary': 'Input expectations only, not inference results. Real ONNX/OCR output must be measured. Not factory footage or an accuracy benchmark.'}
    (OUT/'manifest.json').write_text(json.dumps(manifest, indent=2)+'\n')


if __name__ == '__main__':
    main()
