#!/usr/bin/env python3
"""Build local CJK UI subsets from the official Tier0 IBM Plex SC fonts.
Usage: python3 scripts/subset-ui-fonts.py /path/to/Tier0-Design-System/fonts
Requires fonttools[woff]. Dynamic glyphs outside the UI corpus use OS fallbacks.
"""
from pathlib import Path
import sys
from fontTools import subset

root = Path(__file__).resolve().parent.parent
source = Path(sys.argv[1])
output = root / 'web/src/assets/fonts'
corpus = ''.join(p.read_text() for p in (root / 'web/src').rglob('*') if p.suffix in {'.ts', '.tsx'})
chars = sorted({ord(c) for c in corpus if 0x2E80 <= ord(c) <= 0x9FFF or 0xF900 <= ord(c) <= 0xFAFF or 0xFE30 <= ord(c) <= 0xFFEF})
output.mkdir(parents=True, exist_ok=True)
rules = ['/* Official IBM Plex Sans SC, OFL license in assets/fonts. Generated by scripts/subset-ui-fonts.py. */']
for weight, css_weight in [('Regular', '400'), ('Medium', '500 700')]:
    opts = subset.Options()
    opts.flavor = 'woff2'
    font = subset.load_font(str(source / f'IBMPlexSansSC-{weight}.ttf'), opts)
    sub = subset.Subsetter(options=opts)
    sub.populate(unicodes=chars)
    sub.subset(font)
    # OFL reserves Plex; give the modified subset its own family identity.
    names = {1: 'Plantbot Sans SC UI', 2: weight, 3: f'PlantbotSansSCUI-{weight}', 4: f'Plantbot Sans SC UI {weight}', 6: f'PlantbotSansSCUI-{weight}', 16: 'Plantbot Sans SC UI', 17: weight}
    for record in font['name'].names:
        if record.nameID in names:
            record.string = names[record.nameID].encode(record.getEncoding())
    subset.save_font(font, str(output / f'PlantbotSansSCUI-{weight}.woff2'), opts)
    rules.append("@font-face {\n  font-family: 'Plantbot Sans SC UI';\n  src: url('../assets/fonts/PlantbotSansSCUI-" + weight + ".woff2') format('woff2');\n  font-weight: " + css_weight + ";\n  font-style: normal;\n  font-display: swap;\n  unicode-range: " + ','.join(f'U+{c:X}' for c in chars) + ";\n}")
(root / 'web/src/styles/fonts.css').write_text('\n'.join(rules) + '\n')
print(f'{len(chars)} CJK UI glyphs; fonts generated in {output}')
